# Generated by Django 4.1.2 on 2022-10-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="file",
            name="itin",
            field=models.CharField(max_length=11),
        ),
    ]
